### ISSUE TITLE
Attempted to rotate screen 180 degrees destroyed my distro.

### ISSUE THREAD

**Issue by brooksdra** [AsahiLinux/linux#117]
My Samsung LU28E590DS/AZ monitor is installed upside down. So when I connect a computer to it, I first must adjust the OS's display settings to rotate 180 degrees. This works fine on Windows 10, Mac x86, and Dual Boot Mac M1, but it broke my Dual Boot Asahi Linux running on the same M1.

Now, when I boot to the Asahi Linux image, I get an upside-down login page. After supplying my password, the screen flips to the correct 180-degree orientation and shows the initial K progress bar. The progress bar stops at about 80%, and nothing else happens.

Even when I return to a standard monitor, the same problems occur. At this stage, the installation is unusable.

I tried to SSH into a terminal from another computer to see if the SSH service had started up, but the connection was refused.

I'm not sure what to do next, but with assistance, I am willing to help diagnose the problem.
If that isn't needed, are there any instructions for getting into a safe or recovery mode to reset the display settings, or maybe a way factory reset the installation as it was originally installed?

**Comment by jannau** [comment]
Did you configure the screen as rotated in KDE's Display settings? I wasn't even able to configure that. Systemsettings rotated the screen but crashed before it could show the confirm/revert new settings dialog.

The display settings are stored in `.local/share/kscreen`. If you can remove that directory KDE should be working again with a not rotated display..

With the display and GPU drivers (see https://asahilinux.org/2022/12/gpu-drivers-now-in-asahi-linux/) screen rotation should work.

**Comment by brooksdra** [comment]
How do I access .local/share/kscreen without? When the Kstartup screen locks up, I still don't seem to have ssh access.

Is there a way to delete this directory while botted into the mac os ?

**Comment by jannau** [comment]
I think KDE uses different screen configurations for X11 and Wayland. If you select the not active one (`Plasma (X11)` or Plasma (Wayland)`) as Session in top left corner you should be able to log on.
If this doesn't work you can alternatively switch to a text console using `fn` + `control` + `option` + `F3` (fro `3` on the Macbook Pros with Touchbar), log in with you user name and password and move to directory to another place.
